# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank='', default=''),
        ),
    ]
