# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-30 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170611_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, through='blog.CategoryToPost', to='blog.Category'),
        ),
    ]
